config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get 'create' => 'posts#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :posts

  
  
  
 
end

app/models/post.rb
class Post < ActiveRecord::Base
    validates :title, presence: true
    validates :body, presence: true
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
    attr_accessor :remember_token
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: {maximum: 50}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
     validates :email, presence: true, length: {maximum: 255}, 
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    has_many :posts
    
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
    
    def User.new_token
        SecureRandom.urlsafe_base64
    end
    
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end
    
    def authenticated?(remember_token)
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
    
    def forget
        update_attribute(:remember_digest, nil)
    end

        
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :new]
  
  def index
    @posts = Post.order(created_at: :desc).paginate(page: params[:page])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:success] = "Post successfully created!"
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  private
    
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in"
        redirect_to login_url
      end
    end
    
    def post_params
      params.require(:post).permit(:title, :body)
    end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user) 
      redirect_to root_url
      flash[:success] = "You're logged in!"
    else 
      flash.now[:danger] = "Invalid email/password combination"
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to root_url
    flash[:success] = "You're logged out!"
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    def log_in(user)
        session[:user_id] = user.id
    end
    
    def current_user
        if (user_id = session[:user_id])
            @current_user ||= User.find_by(id: user_id)
        elsif (user_id = cookies.signed[:user_id])
            user = User.find_by(id: user_id)
            if user && user.authenticated?(cookies[:remember_token])
                log_in user
                @current_user = user
            end
        end
    end
    
    def logged_in?
        !current_user.nil?
    end
    
    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end   
    
    def log_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end
    
    def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end
    
end

app/views/layouts/_footer.html.erb
<footer class='footer'>
    <small>
        The 'Member's Only' project. Thanks to 
        <a href="http://www.theodinproject.com">The Odin Project</a>
        for the idea!
    </small>
<nav>
    <ul>
        <li><a href="https://github.com/jonjperkins/embarassing-gossip-site">Check out the github repo here.</a></li>
    </ul>
</nav>
        
    </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div id="logo">Gossip site!</div>
    <div class="container">
      
      <nav>
        <ul class="nav navbar-nav navbar-right">
          
          <% if logged_in? %>
          <li><a href="https://github.com/jonjperkins/embarassing-gossip-site">Github Repo</a></li>
          <li><%= link_to "Home", root_url %></li>
            <li><%= link_to "Log out", logout_path, method: 'delete' %></li>
  
          <% else %>
            <li><a href="https://github.com/jonjperkins/embarassing-gossip-site">Github Repo</a></li>
            <li><%= link_to "Home", root_url %></li>
            <li><%= link_to "Log in", login_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
 </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | The Gossip Site!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <%flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
<%= yield %>

</body>
<%= render 'layouts/footer' %>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<% provide(:title, "Home") %>
<h1>Welcome to the Gossip Site!</h1>

<h3>This is a great place to post all
your juicy gossip. Wow, soooo much dramaaaaaa!</h3> 
<h3>But there's a catch. <em>If you want
to see who authored a post, you have to be signed in!</em></h3>

<br>
<br>

<%if logged_in? %>
 <div class='text-center'><%= link_to "Create a New Post", create_path, class: 'btn btn-primary' %></div>
 <br>
<%else%>
<% end %>
 
 
<div id="container" class="box">
  <%= will_paginate %>
  <p>
    <% @posts.each do |post| %>
      <div id="titles"><%= post.title %></div> 
         <h5><%= "Post created on " + post.created_at.strftime("%d %b. %Y. %H:%M") %></h5>
         <br>
      <h4><%= post.body %> </h4>
      <% if logged_in? %>
        <% user = User.find(post.user_id) %><br>
        <em> <%= "This post was authored by " + user.name %></em><br>
    
      <% else %>
        <br>
        <%= link_to "Log in", create_path %>
        <em><%= "to see who authored this post." %></em> <br>
      <% end %>
  </p>
    <% end %>
  

<%= will_paginate %>
</div>

app/views/posts/new.html.erb
<% provide(:title, "Create post") %>
<h1>Create a post</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@post) do |f| %>
    <%= render 'shared/error_messages' %>
    
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
      
      <%= f.label :body %>
      <%= f.text_field :body, class: 'form-control' %>
      
      <%= f.submit "Submit my post", class: "btn btn-primary" %>
      <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@post.errors.count, "error") %>.
    </div>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>